apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: large-raven-go
  janus-idp.io/tekton: large-raven-go
  backstage.io/kubernetes-id: large-raven-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: large-raven-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
