apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: large-raven-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: large-raven-go 
  name: large-raven-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: large-raven-go 
